spring:
  application:
    name: backend

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  datasource:
    url: jdbc:mysql://localhost:3306/eventosbd?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # en dev que cree/actualice las tablas
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect   # MySQLDialect (MySQL8Dialect está deprecated)
        format_sql: true
        jdbc.time_zone: UTC
    show-sql: true

  jackson:
    time-zone: America/Argentina/Buenos_Aires

  h2:
    console:
      enabled: true
      path: /h2-console

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  baseline-version: 0

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
