spring:
  application:
    name: backend

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  datasource:
    url: jdbc:mysql://localhost:3306/eventosbd?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate      # Flyway controla el esquema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect   # MySQLDialect (MySQL8Dialect está deprecated)
        format_sql: true
        jdbc.time_zone: UTC
    show-sql: true

  jackson:
    time-zone: America/Argentina/Buenos_Aires

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:false}
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
jwt:
  secret: ${JWT_SECRET:aaee89681dd2ffeec808837802a9fdb19b157c71aea36e1886e42c7b2fe0fd7c}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 minutes by default
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days by default